# Generated by Django 5.2.8 on 2025-12-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_app', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
